name: Jest CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Jest GitHub Action
        uses: willcaul/jest-github-action@v1.0.2
        with:
          coverage-comment: true
